### ISSUE TITLE
v0.6.0 regression - No module named 'src' error

### ISSUE THREAD

**Issue by msradam** [Tam-Lin/zos-utilities#2]
I installed zos-utilities 0.6.0 and imported the CPC and LPAR structures in my code as follows:
```
from zos_utilities.cpc import CPC
from zos_utilities.lpar import LPAR
```

This code works fine in v0.5.3.

In v0.6.0, it returns the following, and my script halts.

```
Traceback (most recent call last):
  File "/Users/amrahman/lparlist/lparlist.py", line 14, in <module>
    from zos_utilities.lpar import LPAR
  File "/Users/amrahman/lparlist/env/lib/python3.9/site-packages/zos_utilities/lpar.py", line 9, in <module>
    from .data_set import DataSet
  File "/Users/amrahman/lparlist/env/lib/python3.9/site-packages/zos_utilities/data_set.py", line 5, in <module>
    from src.zos_utilities.dasd_volume import DasdVolume
ModuleNotFoundError: No module named 'src'
```

Running on Python 3.9.
```
❯ python3                                                                                                                                                         zos-utilities -> src-bugfix
Python 3.9.6 (default, May  7 2023, 23:32:44) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
```

**Comment by Tam-Lin** [comment]
Let me see if I can figure out what changed; I'm not seeing that in any of my tests.

**Comment by Tam-Lin** [comment]
Should be fixed in 0.6.1.
